import { useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { CalendarDays, CreditCard, KeyRound, MapPin, Ticket } from 'lucide-react';
import { api, dateTime, money } from '../lib/api';

export function PortalPage() {
  const [data,setData]=useState<any>(null);
  const lookup=useMutation({mutationFn:(body:any)=>api<any>('/public/portal/lookup',{method:'POST',body:JSON.stringify(body)}),onSuccess:setData});
  const payBalance=useMutation({mutationFn:(code:string)=>api<{session:{url:string}}>('/public/payments/start',{method:'POST',body:JSON.stringify({registrationCode:code,paymentKind:'BALANCE'})}),onSuccess:r=>location.href=r.session.url});
  const cancel=useMutation({mutationFn:(body:any)=>api('/public/cancellation-requests',{method:'POST',body:JSON.stringify(body)}),onSuccess:()=>alert('בקשת הביטול התקבלה ותטופל בהתאם למדיניות ולדין.')});
  return <div className="portal-page section-pad"><div className="page-hero"><span className="eyebrow">MY DANCE SPACE</span><h1>האזור שלי</h1><p>הזיני דוא״ל וקוד הרשמה אחד. המערכת תציג את היסטוריית הסדנאות, הכרטיסיות והמנויים שלך.</p></div><div className="portal-card"><form onSubmit={e=>{e.preventDefault();lookup.mutate(Object.fromEntries(new FormData(e.currentTarget)))}}><div className="form-grid"><label>דוא״ל<input name="email" type="email" required/></label><label className="field-sm">קוד הרשמה<input name="registrationCode" required placeholder="EZ-XXXXXXX"/></label></div>{lookup.error&&<div className="error-box">לא נמצאה הרשמה עם הפרטים האלה.</div>}<button className="button primary full">איתור הפרטים</button></form></div>
    {data&&<><section className="portal-section"><h2>הסדנאות שלי</h2><div className="portal-list">{data.registrations.map((r:any)=><article className="portal-result" key={r.registration_code}><span className={`status-chip ${r.status.toLowerCase()}`}>{r.status}</span><h3>{r.title}</h3><div><CalendarDays/> {dateTime(r.starts_at)}</div><div><MapPin/> {r.location_name}, {r.location_address}</div><div><Ticket/> {r.participant_count} משתתפים · שולם {money(r.amount_paid_agorot)}</div><strong>קוד: {r.registration_code}</strong>{r.balance_agorot>0&&r.status==='DEPOSIT_PAID'&&<button className="button primary small" onClick={()=>payBalance.mutate(r.registration_code)}><CreditCard/> תשלום יתרה {money(r.balance_agorot)}</button>}<details><summary>בקשת ביטול</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);cancel.mutate({registrationCode:r.registration_code,email:data.registrations[0]?.email||f.get('email'),reason:f.get('reason')})}}><input name="email" type="email" placeholder="דוא״ל לאימות" required/><textarea name="reason" placeholder="סיבת הביטול" required/><button className="button outline small">שליחת בקשה</button></form></details></article>)}</div></section>
    <section className="portal-section"><h2>כרטיסיות ומנויים</h2><div className="portal-list">{data.entitlements.length?data.entitlements.map((e:any)=><article className="portal-result" key={e.id}><KeyRound/><h3>{e.type==='PASS'?'כרטיסייה':'מנוי'}</h3><div className="confirmation-code small-code">{e.code}</div><span>{e.credits_remaining} קרדיטים נותרו</span><span>בתוקף עד {dateTime(e.valid_until)}</span><span className={`status-chip ${e.status.toLowerCase()}`}>{e.status}</span></article>):<p>אין כרטיסיות או מנויים פעילים.</p>}</div></section></>}
  </div>;
}
