import { ArrowLeft, ArrowRight, Camera, Film, Images, ShieldCheck, Sparkles, TicketCheck, Users } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { api } from '../lib/api';
import type { GalleryItem, SiteData, Workshop } from '../lib/types';
import { WorkshopCard } from '../components/WorkshopCard';
import { ErrorBox, Loading } from '../components/Loading';
import { usePublicTheme } from '../lib/theme';
import { useLanguage } from '../lib/language';

export function HomePage() {
  const theme=usePublicTheme(); const {language,t}=useLanguage(); const site=useQuery({queryKey:['site'],queryFn:()=>api<SiteData>('/public/site')}); const workshops=useQuery({queryKey:['workshops'],queryFn:()=>api<{workshops:Workshop[]}>('/public/workshops')}); const gallery=useQuery({queryKey:['gallery'],queryFn:()=>api<{items:GalleryItem[]}>('/public/gallery')});
  if(site.isLoading||workshops.isLoading)return <Loading label={t('מכינים את הרחבה...','Getting the studio ready...')}/>; if(site.error||workshops.error)return <ErrorBox error={site.error||workshops.error}/>;
  const home=site.data?.content.home||{}; const instructor=site.data?.content.instructor||{}; const isModern=theme==='modern'; const galleryImages=(gallery.data?.items||[]).filter(item=>item.media_type==='IMAGE'); const selectedGalleryImage=galleryImages.find(item=>item.id===home.heroGalleryItemId)?.public_url||galleryImages[0]?.public_url||''; const heroImg=home.heroImageSource==='GALLERY'?(selectedGalleryImage||home.heroImage||'/images/hero.jpg'):(home.heroImage||selectedGalleryImage||(isModern?'/images/hero.jpg':'')); const portraitImg=instructor.portraitUrl||(isModern?'/images/instructor.jpg':''); const Arrow=language==='he'?ArrowLeft:ArrowRight;
  const pick=(key:string,heFallback:string,enFallback:string)=>language==='en'?(home[`${key}En`]||enFallback):(home[key]||heFallback); const ipick=(key:string,heFallback:string,enFallback:string)=>language==='en'?(instructor[`${key}En`]||enFallback):(instructor[key]||heFallback);
  return <>
    {(language==='en'?home.announcementEn:home.announcement)&&<div className="announcement">{language==='en'?home.announcementEn:home.announcement}</div>}
    <section className="hero section-pad"><div className="hero-copy"><span className="eyebrow">{pick('eyebrow','MOVE. FEEL. GROW.','MOVE. FEEL. GROW.')}</span><h1 className="hero-title-stack"><span className={`hero-title-top hero-font-${String(home.heroTitleTopFont||'BODY').toLowerCase()} hero-top-${String(home.heroTitleTopSize||'MEDIUM').toLowerCase()}`}>{pick('heroTitleTop','COME DANCE WITH','COME DANCE WITH')}</span><span className={`hero-title-main hero-font-${String(home.heroTitleMainFont||'DISPLAY').toLowerCase()} hero-main-${String(home.heroTitleMainSize||'XL').toLowerCase()} ${home.heroTitleMainBold===false?'':'is-bold'}`}>{pick('heroTitleMain','EDEN ZINO','EDEN ZINO')}</span></h1><p>{pick('heroSubtitle','סדנאות ריקוד מקצועיות, אנרגטיות ומדויקות בהנחיית עדן זינו.','Professional, energetic and precise dance workshops led by Eden Zino.')}</p><div className="hero-actions"><Link className="button primary" to="/workshops">{pick('ctaPrimary','לסדנאות הקרובות','Upcoming workshops')} <Arrow/></Link><Link className="button ghost" to="/workshops#code">{pick('ctaSecondary','יש לי קוד סדנה','I have a workshop code')}</Link></div><div className="trust-row"><span><ShieldCheck/> {t('תשלום מאובטח','Secure payment')}</span><span><TicketCheck/> {t('אישור מיידי','Instant confirmation')}</span><span><Users/> {t('קבוצות מוגבלות','Limited groups')}</span></div></div><div className="hero-visual" style={heroImg?{backgroundImage:`url(${heroImg})`}:undefined}>{isModern?<div className="vertical-copy">EDEN ZINO · DANCE WORKSHOPS</div>:!heroImg&&<><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="dance-letter">E</div><div className="vertical-copy">EDEN ZINO · DANCE WORKSHOPS</div></>}</div></section>
    <section className="section-pad dark-section"><div className="section-heading"><span className="eyebrow">UPCOMING</span><h2>{t('הסדנאות הקרובות','Upcoming workshops')}</h2><p>{t('בחרו סדנה, שמרו מקום והגיעו לרקוד.','Choose a workshop, save your spot and come dance.')}</p></div><div className="workshop-grid">{workshops.data?.workshops.slice(0,3).map(w=><WorkshopCard key={w.id} workshop={w}/>)}</div>{!workshops.data?.workshops.length&&<div className="empty-state"><Sparkles/><h3>{t('הסדנה הבאה בדרך','The next workshop is on the way')}</h3><p>{t('עדן תפרסם כאן את הסדנאות החדשות דרך ממשק הניהול.','New workshops will appear here as soon as Eden publishes them.')}</p></div>}<div className="center-action"><Link className="button light" to="/workshops">{t('לכל הסדנאות','All workshops')} <Arrow/></Link></div></section>
    <GalleryPreview/>
    <section className="section-pad instructor-section"><div className="portrait-panel" style={portraitImg?{backgroundImage:`url(${portraitImg})`}:undefined}>{!portraitImg&&<div className="portrait-placeholder"><span>EZ</span><small>{t('העלי תמונת תדמית דרך הניהול','Upload a portrait from the admin panel')}</small></div>}</div><div className="instructor-copy"><span className="eyebrow">MEET YOUR INSTRUCTOR</span><h2>{ipick('name','עדן זינו','Eden Zino')}</h2><h3>{ipick('headline','מדריכה, יוצרת ורקדנית','Instructor, creator and dancer')}</h3><p>{ipick('bio','הוסיפי כאן דרך ממשק הניהול את הרקע המקצועי והאישי של עדן.','Add Eden’s professional and personal background from the admin panel.')}</p><blockquote>{ipick('teachingApproach','הוסיפי כאן את שיטת הלימוד, הערכים והחוויה שהתלמידים מקבלים.','Add the teaching approach, values and student experience from the admin panel.')}</blockquote><a className="button outline" href={instructor.instagramUrl||'https://www.instagram.com/eden_zinooo/?hl=en'} target="_blank" rel="noreferrer"><Camera/> Instagram</a></div></section>
    <section className="section-pad code-banner"><div><span className="eyebrow">PRIVATE WORKSHOP</span><h2>{t('קיבלת קוד סדנה?','Got a workshop code?')}</h2><p>{t('הזיני אותו וקבלי מיד את כל הפרטים, המחיר וההרשמה.','Enter it to instantly view details, price and registration.')}</p></div><CodeBox/></section>
  </>;
}

function CodeBox(){const {language,t}=useLanguage();const Arrow=language==='he'?ArrowLeft:ArrowRight;return <form className="code-box" onSubmit={e=>{e.preventDefault();const code=new FormData(e.currentTarget).get('code');if(code)location.href=`/w/${String(code).trim().toUpperCase()}`;}}><label htmlFor="home-code">{t('קוד הסדנה','Workshop code')}</label><div><input id="home-code" name="code" placeholder={t('לדוגמה: EZ7K4M2','Example: EZ7K4M2')} required/><button className="button primary">{t('פתיחת סדנה','Open workshop')} <Arrow/></button></div></form>}

function GalleryPreview(){const {language,t,localize}=useLanguage();const Arrow=language==='he'?ArrowLeft:ArrowRight;const query=useQuery({queryKey:['gallery'],queryFn:()=>api<{items:GalleryItem[]}>('/public/gallery')});const items=query.data?.items.slice(0,6)??[];if(!items.length)return null;return <section className="section-pad studio-gallery"><div className="section-heading"><span className="eyebrow">INSIDE THE STUDIO</span><h2>{t('רגעים מהרחבה','Moments from the floor')}</h2><p>{t('תמונות וסרטונים מהסדנאות, מהתנועה ומהקהילה.','Photos and videos from workshops, movement and community.')}</p></div><div className="home-gallery-grid">{items.map(item=><Link className="home-gallery-item" to="/gallery" key={item.id} aria-label={t(`פתיחת הגלריה: ${localize(item,'title')||'רגע מהרחבה'}`,`Open gallery: ${localize(item,'title')||'Dance moment'}`)}>{item.media_type==='VIDEO'?<video muted playsInline preload="metadata"><source src={item.public_url} type={item.content_type}/></video>:<img src={item.public_url} alt={localize(item,'alt_text')||localize(item,'title')||t('רגע מהרחבה','Dance moment')} loading="lazy"/>}<span>{item.media_type==='VIDEO'?<Film/>:<Images/>}</span>{localize(item,'title')&&<b>{localize(item,'title')}</b>}</Link>)}</div><div className="center-action"><Link className="button outline" to="/gallery">{t('לגלריה המלאה','Full gallery')} <Arrow/></Link></div></section>}
