import { useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { BadgeCheck, CreditCard, Repeat2, Ticket } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { api, money } from '../lib/api';
import { useLanguage } from '../lib/language';
import { ErrorBox, Loading } from '../components/Loading';

type Product = { id:string; name:string; name_en?:string; description:string; description_en?:string; price_agorot:number; credits?:number; validity_days?:number; billing_interval?:string; included_credits?:number; discount_percent?:number };

export function ProductsPage(){const {language,t}=useLanguage();const q=useQuery({queryKey:['products'],queryFn:()=>api<{membershipPlans:Product[];passProducts:Product[]}>('/public/products')});const [selected,setSelected]=useState<{type:'PASS'|'MEMBERSHIP';product:Product}|null>(null);const buy=useMutation({mutationFn:(body:any)=>api<{session:{url:string}}>('/public/orders',{method:'POST',body:JSON.stringify(body)}),onSuccess:r=>location.href=r.session.url});if(q.isLoading)return <Loading/>;if(q.error||!q.data)return <ErrorBox error={q.error||new Error(t('לא ניתן לטעון מוצרים','Unable to load products'))}/>;const name=(p:Product)=>language==='en'?(p.name_en||p.name):p.name;return <div className="products-page section-pad"><div className="page-hero"><span className="eyebrow">PASSES & MEMBERSHIPS</span><h1>{t('יותר ריקוד. פחות התעסקות.','More dancing. Less hassle.')}</h1><p>{t('כרטיסיות ומנויים נרכשים אונליין ומפיקים קוד אישי לשימוש בהרשמה לסדנאות.','Buy passes and memberships online and receive a personal code for workshop registration.')}</p></div><section><div className="section-heading"><Ticket/><h2>{t('כרטיסיות','Passes')}</h2></div><div className="workshop-grid">{q.data.passProducts.map(p=><ProductCard key={p.id} product={p} type="PASS" onBuy={()=>setSelected({type:'PASS',product:p})}/>)}</div></section><section><div className="section-heading"><Repeat2/><h2>{t('מנויים','Memberships')}</h2></div><div className="workshop-grid">{q.data.membershipPlans.map(p=><ProductCard key={p.id} product={p} type="MEMBERSHIP" onBuy={()=>setSelected({type:'MEMBERSHIP',product:p})}/>)}</div></section>{selected&&<div className="modal-backdrop"><div className="modal compact-modal"><button className="modal-close" onClick={()=>setSelected(null)}>×</button><span className="eyebrow">SECURE CHECKOUT</span><h2>{name(selected.product)}</h2><strong className="product-price">{money(selected.product.price_agorot,'ILS',language)}</strong><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);buy.mutate({productType:selected.type,productId:selected.product.id,fullName:f.get('fullName'),email:f.get('email'),phone:f.get('phone')})}}><div className="form-grid"><label>{t('שם מלא','Full name')}<input name="fullName" required/></label><label>{t('דוא״ל','Email')}<input name="email" type="email" required/></label><label>{t('טלפון','Phone')}<input name="phone" required/></label></div>{buy.error&&<ErrorBox error={buy.error}/>}<button className="button primary full" disabled={buy.isPending}><CreditCard/> {buy.isPending?t('פותח תשלום...','Opening payment...'):t('המשך לתשלום','Continue to payment')}</button></form></div></div>}</div>}

function ProductCard({product,type,onBuy}:{product:Product;type:'PASS'|'MEMBERSHIP';onBuy:()=>void}){const {language,t}=useLanguage();const name=language==='en'?(product.name_en||product.name):product.name;const description=language==='en'?(product.description_en||product.description):product.description;const interval=(v?:string)=>v==='MONTHLY'?t('חודשי','Monthly'):v==='QUARTERLY'?t('רבעוני','Quarterly'):t('שנתי','Yearly');return <article className="product-card"><div className="product-icon">{type==='PASS'?<Ticket/>:<Repeat2/>}</div><span className="eyebrow">{type}</span><h3>{name}</h3><p>{description}</p><ul>{type==='PASS'?<><li><BadgeCheck/> {product.credits} {t('כניסות','entries')}</li><li><BadgeCheck/> {t('תוקף','Valid for')} {product.validity_days} {t('ימים','days')}</li></>:<><li><BadgeCheck/> {product.included_credits} {t('קרדיטים בתקופה','credits per period')}</li><li><BadgeCheck/> {t('חיוב','Billing')}: {interval(product.billing_interval)}</li>{Boolean(product.discount_percent)&&<li><BadgeCheck/> {product.discount_percent}% {t('הנחה','discount')}</li>}</>}</ul><strong>{money(product.price_agorot,'ILS',language)}</strong><button className="button primary full" onClick={onBuy}>{t('רכישה','Buy')}</button></article>}

export function ProductResultPage(){const {t}=useLanguage();const [params]=useSearchParams();const code=params.get('order')||'';const access=params.get('access')||'';const q=useQuery({queryKey:['order-result',code],queryFn:()=>api<{order:any}>(`/public/orders/${encodeURIComponent(code)}/status?access=${encodeURIComponent(access)}`),enabled:!!code,refetchInterval:x=>(x.state.data as any)?.order?.status==='PAID'?false:2000});if(q.isLoading)return <Loading label={t('בודקים את הרכישה...','Checking your purchase...')}/>;if(q.error||!q.data)return <ErrorBox error={q.error||new Error(t('הזמנה לא נמצאה','Order not found'))}/>;const o=q.data.order;const paid=o.status==='PAID';return <div className="center-page result-page">{paid?<BadgeCheck className="success-icon" size={64}/>:<CreditCard className="error-icon" size={60}/>}<span className="eyebrow">PRODUCT ORDER</span><h1>{paid?t('הרכישה הושלמה','Purchase complete'):t('ממתינים לאישור התשלום','Waiting for payment confirmation')}</h1>{paid&&<><p>{t('הקוד האישי נשלח גם בדוא״ל. שמרו אותו לשימוש בהרשמה.','Your personal code was also sent by email. Keep it for registration.')}</p><div className="confirmation-code">{o.metadata?.issuedCode||t('מפיקים קוד...','Generating code...')}</div></>}<div className="hero-actions"><Link className="button primary" to="/my-registration">{t('לאזור שלי','My area')}</Link><Link className="button ghost" to="/products">{t('חזרה למוצרים','Back to products')}</Link></div></div>}
