import { useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Camera, Mail, Phone, ShieldCheck } from 'lucide-react';
import { useParams } from 'react-router-dom';
import { api } from '../lib/api';
import { useLanguage } from '../lib/language';
import type { SiteData } from '../lib/types';
import { ErrorBox, Loading } from '../components/Loading';

export function ContactPage(){const {t}=useLanguage();const [done,setDone]=useState(false);const site=useQuery({queryKey:['site'],queryFn:()=>api<SiteData>('/public/site')});const settings=site.data?.settings||{};const mutation=useMutation({mutationFn:(body:any)=>api('/public/contact',{method:'POST',body:JSON.stringify(body)}),onSuccess:()=>setDone(true)});return <div className="contact-page section-pad"><div className="page-hero"><span className="eyebrow">LET'S TALK</span><h1>{t('יש שאלה? דברו איתנו','Have a question? Let’s talk')}</h1><p>{t('בנוגע לסדנה, הרשמה פרטית, שיתוף פעולה או אירוע מיוחד.','About a workshop, private booking, collaboration or special event.')}</p></div><div className="contact-grid"><div className="contact-info"><h2>Eden Zino</h2><a href={`mailto:${settings.contact_email||'hello@example.co.il'}`}><Mail/> {settings.contact_email||'hello@example.co.il'}</a>{settings.contact_phone&&<a href={`tel:${settings.contact_phone}`}><Phone/> {settings.contact_phone}</a>}<a href={settings.instagram_url||'https://www.instagram.com/eden_zinooo/?hl=en'} target="_blank" rel="noreferrer"><Camera/> @eden_zinooo</a></div><div className="contact-form">{done?<div className="success-box">{t('ההודעה נשלחה. נחזור אליך בהקדם.','Message sent. We’ll get back to you soon.')}</div>:<form onSubmit={e=>{e.preventDefault();mutation.mutate(Object.fromEntries(new FormData(e.currentTarget)))}}><div className="form-grid"><label>{t('שם','Name')}<input name="name" required/></label><label>{t('דוא״ל','Email')}<input name="email" type="email" required/></label><label>{t('טלפון','Phone')}<input name="phone"/></label></div><label>{t('הודעה','Message')}<textarea name="message" rows={6} required/></label><button className="button primary">{t('שליחת הודעה','Send message')}</button></form>}</div></div></div>}

export function LegalPage(){const {language,t}=useLanguage();const {type='TERMS'}=useParams();const query=useQuery({queryKey:['site'],queryFn:()=>api<SiteData>('/public/site')});if(query.isLoading)return <Loading/>;if(query.error)return <ErrorBox error={query.error}/>;const doc=query.data?.legal.find(d=>d.type===type) as any;const title=language==='en'?(doc?.title_en||doc?.title):doc?.title;const content=language==='en'?(doc?.content_en||doc?.content):doc?.content;return <article className="legal-page section-pad"><span className="eyebrow">LEGAL</span><h1>{title||t('מסמך לא נמצא','Document not found')}</h1>{doc&&<small>{t('גרסה','Version')}: {doc.version}</small>}<div className="legal-content">{content||t('המסמך טרם פורסם.','This document has not been published yet.')}</div>{type==='PRIVACY'&&<PrivacyRequest/>}</article>}

function PrivacyRequest(){const {t}=useLanguage();const [done,setDone]=useState(false);const request=useMutation({mutationFn:(body:any)=>api('/public/privacy-requests',{method:'POST',body:JSON.stringify(body)}),onSuccess:()=>setDone(true)});return <section className="privacy-request"><ShieldCheck/><h2>{t('בקשה בנוגע למידע אישי','Personal data request')}</h2>{done?<div className="success-box">{t('הבקשה התקבלה ותועבר לטיפול.','Your request was received and will be reviewed.')}</div>:<form onSubmit={e=>{e.preventDefault();request.mutate(Object.fromEntries(new FormData(e.currentTarget)))}}><div className="form-grid"><label>{t('דוא״ל','Email')}<input name="email" type="email" required/></label><label>{t('סוג בקשה','Request type')}<select name="requestType"><option value="ACCESS">{t('עיון במידע','Access')}</option><option value="CORRECTION">{t('תיקון מידע','Correction')}</option><option value="DELETION">{t('מחיקה/אנונימיזציה','Deletion / anonymization')}</option><option value="MARKETING_OPT_OUT">{t('הסרה משיווק','Marketing opt-out')}</option></select></label></div><label>{t('פרטים','Details')}<textarea name="details" rows={4}/></label><button className="button primary">{t('שליחת בקשה','Send request')}</button></form>}</section>}
